package com.example.wiki.req;




import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ebook
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class EbookReq{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.id
     *
     * @mbg.generated
     */
    @Min(value = 1, message = "id couldn't be smaller than 1")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.name
     *
     * @mbg.generated
     */
    private String name;

    @Override
    public String toString() {
        return "EbookReq{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.category1_id
     *
     * @mbg.generated
     */

}