package com.example.wiki.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table portfolio
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Portfolio implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfolio.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfolio.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfolio.link
     *
     * @mbg.generated
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfolio.linkimg
     *
     * @mbg.generated
     */
    private String linkimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfolio.id
     *
     * @return the value of portfolio.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfolio.id
     *
     * @param id the value for portfolio.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfolio.category
     *
     * @return the value of portfolio.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfolio.category
     *
     * @param category the value for portfolio.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfolio.link
     *
     * @return the value of portfolio.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfolio.link
     *
     * @param link the value for portfolio.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfolio.linkimg
     *
     * @return the value of portfolio.linkimg
     *
     * @mbg.generated
     */
    public String getLinkimg() {
        return linkimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfolio.linkimg
     *
     * @param linkimg the value for portfolio.linkimg
     *
     * @mbg.generated
     */
    public void setLinkimg(String linkimg) {
        this.linkimg = linkimg;
    }
}