package com.example.wiki.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table watchtimes
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Watchtimes implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watchtimes.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watchtimes.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watchtimes.times
     *
     * @mbg.generated
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watchtimes.contacttimes
     *
     * @mbg.generated
     */
    private Integer contacttimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watchtimes.contactalltimes
     *
     * @mbg.generated
     */
    private Integer contactalltimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watchtimes.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watchtimes.id
     *
     * @return the value of watchtimes.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watchtimes.id
     *
     * @param id the value for watchtimes.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watchtimes.description
     *
     * @return the value of watchtimes.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watchtimes.description
     *
     * @param description the value for watchtimes.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watchtimes.times
     *
     * @return the value of watchtimes.times
     *
     * @mbg.generated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watchtimes.times
     *
     * @param times the value for watchtimes.times
     *
     * @mbg.generated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watchtimes.contacttimes
     *
     * @return the value of watchtimes.contacttimes
     *
     * @mbg.generated
     */
    public Integer getContacttimes() {
        return contacttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watchtimes.contacttimes
     *
     * @param contacttimes the value for watchtimes.contacttimes
     *
     * @mbg.generated
     */
    public void setContacttimes(Integer contacttimes) {
        this.contacttimes = contacttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watchtimes.contactalltimes
     *
     * @return the value of watchtimes.contactalltimes
     *
     * @mbg.generated
     */
    public Integer getContactalltimes() {
        return contactalltimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watchtimes.contactalltimes
     *
     * @param contactalltimes the value for watchtimes.contactalltimes
     *
     * @mbg.generated
     */
    public void setContactalltimes(Integer contactalltimes) {
        this.contactalltimes = contactalltimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watchtimes.date
     *
     * @return the value of watchtimes.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watchtimes.date
     *
     * @param date the value for watchtimes.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}