package com.example.wiki.Resp;


import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserLoginResp implements Serializable {

    private Long id;

    private String token;

    private String date;
    private Long resttime;



    private String loginName;


    private String name;

    @Override
    public String toString() {
        return "UserLoginResp{" +
                "id=" + id +
                ", token='" + token + '\'' +
                ", date='" + date + '\'' +
                ", resttime=" + resttime +
                ", loginName='" + loginName + '\'' +
                ", name='" + name + '\'' +
                '}';
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Long getResttime() {
        return resttime;
    }

    public void setResttime(Long resttime) {
        this.resttime = resttime;
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}