package com.example.wiki.mapper;

import com.example.wiki.entity.AboutContent;
import com.example.wiki.entity.AboutContentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AboutContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    long countByExample(AboutContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    int deleteByExample(AboutContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    int insert(AboutContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    int insertSelective(AboutContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    List<AboutContent> selectByExample(AboutContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    AboutContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AboutContent record, @Param("example") AboutContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AboutContent record, @Param("example") AboutContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AboutContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AboutContent record);
}