package com.example.wiki.mapper;

import com.example.wiki.entity.Portfolio;
import com.example.wiki.entity.PortfolioExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PortfolioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    long countByExample(PortfolioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    int deleteByExample(PortfolioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    int insert(Portfolio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    int insertSelective(Portfolio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    List<Portfolio> selectByExample(PortfolioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    Portfolio selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Portfolio record, @Param("example") PortfolioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Portfolio record, @Param("example") PortfolioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Portfolio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Portfolio record);
}