package com.example.wiki.mapper;

import com.example.wiki.entity.Watchtimes;
import com.example.wiki.entity.WatchtimesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WatchtimesMapper {
    int clearwatchtimes();
    int timesSum();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    long countByExample(WatchtimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    int deleteByExample(WatchtimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    int insert(Watchtimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    int insertSelective(Watchtimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    List<Watchtimes> selectByExample(WatchtimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    Watchtimes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Watchtimes record, @Param("example") WatchtimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Watchtimes record, @Param("example") WatchtimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Watchtimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchtimes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Watchtimes record);
}