package com.example.wiki.mapper;

import com.example.wiki.entity.WikiUser;
import com.example.wiki.entity.WikiUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WikiUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    long countByExample(WikiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    int deleteByExample(WikiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    int insert(WikiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    int insertSelective(WikiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    List<WikiUser> selectByExample(WikiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    WikiUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WikiUser record, @Param("example") WikiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WikiUser record, @Param("example") WikiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WikiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WikiUser record);
}